name: Commit CI

on:
  push:
    branches:
      - '**'
    tags:
      - '![0-9]+.*'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
      - name: Install clang-format 18
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-18
          sudo ln -sf /usr/bin/clang-format-18 /usr/local/bin/clang-format
      - name: Code style lint
        run: make clang-format-lint

  linux:
    needs: lint
    uses: ./.github/workflows/linux-build.yml

  macos:
    needs: lint
    uses: ./.github/workflows/macos-build.yml

  windows:
    needs: lint
    uses: ./.github/workflows/windows-build.yml

  docker:
    needs: lint
    uses: ./.github/workflows/docker-build.yml
